# Generated by Django 4.0.4 on 2022-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='start_date',
            field=models.DateField(default='0001-01-01', null=True),
        ),
    ]
