# Generated by Django 4.0.4 on 2022-08-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_gymuser_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymuser',
            name='date_joined',
        ),
    ]
