# Generated by Django 4.0.4 on 2022-08-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_gymuser_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymuser',
            old_name='member',
            new_name='customer',
        ),
    ]
