# Generated by Django 4.0.4 on 2022-08-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_member_gymuser_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gym_status',
            field=models.BooleanField(default=False),
        ),
    ]
