# Generated by Django 4.0.4 on 2022-08-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_customer_options_customer_hall_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hall')),
            ],
        ),
    ]
