# Generated by Django 4.0.4 on 2022-08-30 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_hallbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='occupant',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='status',
        ),
    ]
